### ISSUE TITLE
[FEATURE]: Contact edit

### ISSUE THREAD

**Issue by LogGits** [AndresMorelos/Invoncify#105]
It would be a good idea to allow for editing contact information as opposed to having to manually rewrite it if a mistake was made.

**Comment by LogGits** [comment]
Oops i didn't notice that one, that's fantastic. It could also be a good idea to have an option to edit when creating an invoice aswell. This could be setup in a way that there is the select and an edit icon to the right of it. I also noticed that editing the recipient doesn't update on the invoice.

**Comment by AndresMorelos** [comment]
@LogGits This will be fixed at v1.30.1
