### ISSUE TITLE
[BUG]: PDF setting are reset after app restart

### ISSUE THREAD

**Issue by chipotledonut** [AndresMorelos/Invoncify#107]
**Describe the bug**
When changing colors, size and so on in PDF view and press save settings, I can see the notification saying settings saved. When I restart the app it's not saved. 

**To Reproduce**
1. Go to 'view invoice' 
2. Click on 'change logo size, color, font size...'
3. Press 'save settings'
4. Restart app
5. Go to 'view invoice'

**Expected behavior**
I would expect my setting to be saved. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 
 - Version: 1.30 AppImage.

**Additional context**
It happens since I started using this app. Many versions ago.

**Comment by AndresMorelos** [comment]
@chipotledonut I will take a look on this.

**Comment by chipotledonut** [comment]
Is it working properly in the deb file?

**Comment by AndresMorelos** [comment]
@chipotledonut This will be fixed at v1.30.1
