### ISSUE TITLE
[BUG]:  Duplicated SubItems at copy an invoice

### ISSUE THREAD

**Issue by mcfalld** [AndresMorelos/Invoncify#117]
**Describe the bug**
When copying an invoice, editing any of the sub-items or the item which contains them causes them to duplicate. 

**To Reproduce**
1. Go to an invoice press the button to make a copy.
2. Then click edit on the copied invoice
3. find the item with subtasks, edit the price of the item, or click on the x to delete subtasks
4. See error which is the subtasks duplicate, many times depending on what you click. including, changing the price, or the quantity

**Expected behavior**
I would expect the subtasks to be unaffected by the changes unless I directly change them

**Screenshots**
![image](https://user-images.githubusercontent.com/32588824/179639919-6938e8c6-8410-454b-a47a-0da4c38cbd06.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 21H2

**Comment by AndresMorelos** [comment]
@mcfalld I'll take a look on this.

**Comment by AndresMorelos** [comment]
I was able to replicate it, so I'll be fixing it this week.
