### ISSUE TITLE
A MineCraft soundpack

### ISSUE THREAD

**Issue by sonalder-darlene** [AndresMorelos/Invoncify#19]
The CS:GO soundpack is amazing, but this could be better.

Thanks for maintaining the Manta app :)

**Comment by AndresMorelos** [comment]
hey @sonalder-darlene, that's could be cool, do you have the tracks? also, if you want to help PRs are welcome

**Comment by sonalder-darlene** [comment]
I can find them,
[Here](https://minecraft.fandom.com/wiki/Category:Sound_effects) are some FX ont he game wiki
[Here](https://www.voicy.network/official-soundboards/Games/minecraft) are all the sounds I think

**Comment by AndresMorelos** [comment]
hey @sonalder-darlene, I added a soundtrack for Minecraft in this PR #20, do you want to test it first? 

To run the app local you will need two terminals:

First Terminal Running:

```shell
 yarn dev
```

Second Terminal Running the program in dev mode:
```shell
yarn start:dev
```


let me know your thoughts

**Comment by sonalder-darlene** [comment]
I'll try let's go !

**Comment by sonalder-darlene** [comment]
I think I miss some dependencies, I've install yarn but I get this error :

Invoncify-main % yarn dev
yarn run v1.22.17
$ webpack --config webpack.config.dev.js --watch
/bin/sh: webpack: command not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by AndresMorelos** [comment]
hey @sonalder-darlene , did you installed the project dependencies? to do this you will need to run:

```shell
yarn install
```

**Comment by sonalder-darlene** [comment]
Thanks that's what I didn't do correctly. This is good I think, I may not eared every sounds but so far so cool !

**Comment by AndresMorelos** [comment]
Ok, I'll release the new version with this sound track
