### ISSUE TITLE
Modify the date

### ISSUE THREAD

**Issue by sonalder-darlene** [AndresMorelos/Invoncify#28]
I would like to be able to modify the date of an invoice so it's not fixed to the date it was created.

In form settings it should have a date that we are able to change as we want.
A button to reset the date to the creation date would be nice to have too.

**Comment by AndresMorelos** [comment]
@sonalder-darlene what that date means to you? I mean the invoice has an option to add a due date

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/6563162/158834525-0cbcef23-368d-4a84-b7e1-ee5d983f9570.png">

also, if you duplicate the invoice the creation date is modified as well

**Comment by AndresMorelos** [comment]
@sonalder-darlene ok, sure, meanwhile I think that you can duplicate the invoice and it will update the creation date
