### ISSUE TITLE
[BUG]: The minecraft sound on start/login is irrelevant and annoying

### ISSUE THREAD

**Issue by sonalder-darlene** [AndresMorelos/Invoncify#40]
**Describe the bug**
I think this sound does not suit with the soundpack and the app in general

**To Reproduce**
1. Open the app
2. Listen to the weird sound on the login screen

**Expected behavior**
Another sound that is better for welcoming the user and more iconic to Minecraft

**Desktop (please complete the following information):**
 - OS: [macOS]
 - Version [12.0.1]

**Additional context**
I will look for a better sound if you want ;)

**Comment by AndresMorelos** [comment]
@sonalder-darlene for sure, could you please look for a better sound?
