### ISSUE TITLE
[BUG]: Statistics showing the wrong currency

### ISSUE THREAD

**Issue by ding0z** [AndresMorelos/Invoncify#43]
**Describe the bug**
The statistics page show the graph based using the Dollar sign even if the currency used is different (in my case British Pound).

**To Reproduce**
Just check the Statistics

**Desktop:**
OS: [macOS]
Version [11.6.5]

**Comment by AndresMorelos** [comment]
@ding0z I was forced to remove the dollar symbol from the statistics, I wasn't able to add a custom symbol there unfortunately since the library used for the graphs has a restriction on the symbols.
