### ISSUE TITLE
[FEATURE]: Allow editing a saved contact

### ISSUE THREAD

**Issue by mcfalld** [AndresMorelos/Invoncify#77]
Feature Request:

Allow for editing a contact after it has been saved

**Comment by AndresMorelos** [comment]
@mcfalld let's split this feature into multiple requests, one feature request per each number. Thanks, I will be reviewing this.

**Comment by mcfalld** [comment]
ok sounds good, i will edit this one and break it up!

**Comment by AndresMorelos** [comment]
@mcfalld I started with the second point, could you please help me split this issue?. I don't want to split it myself because GitHub will not give you a notification when it's resolved

**Comment by mcfalld** [comment]
amazing, thank you!

**Comment by mcfalld** [comment]
just a note, after editing a contact the first time it worked no problem, then went back to edit the same contact a second time and I get 
![image](https://user-images.githubusercontent.com/32588824/174494387-cac3f199-25a4-4422-a743-592f1616f05b.png)

**Comment by AndresMorelos** [comment]
@mcfalld I will take a look, If I found any issue I will open a new one and tag you there.
