### ISSUE TITLE
[BUG]: Invoncify keeps adding itself to Login Items list

### ISSUE THREAD

**Issue by ding0z** [AndresMorelos/Invoncify#78]
**Describe the bug**
Every time the app starts adds itself to the login items list of macOS. I tried to remove it manually but it goes on list on the next run.

**To Reproduce**
Just open it, remove it from the list and open it again.

**Desktop:**
OS: [macOS]
Version [11.7.0]

**Comment by AndresMorelos** [comment]
@ding0z I'll check this soon, I'll keep you posted.

**Comment by AndresMorelos** [comment]
Reference: File to modify https://github.com/AndresMorelos/Invoncify/blob/main/main/auto-start.js
