### ISSUE TITLE
[FEATURE]: Allow qty of zero or a price of zero

### ISSUE THREAD

**Issue by mcfalld** [AndresMorelos/Invoncify#80]
Allow qty of zero/price of zero or if not, let me add sub-items void of qty and price. An example of why this might be useful is perhaps there is a price associated with a range of quantities that id like to let them know about. let's say the range is 1-3 at $5 and 4-10 at $10. Once the customer surpasses the 1-3 range, I don't want them to think I've suddenly changed the price. So, ideally, I could have 4-10 at price $10 qty 0 because they haven't yet scaled up to 4 yet.

Because I can't add items with a qty of 0, I attempted to just add a note, but newline characters are removed automatically so the range of quantities just looks confusing in the note.

ex.
License Management and Administration 1  0    0.00
                                6-10 Licenses -   $30  1  30 30.00
                                11-20 Licenses - $50  0  0    0.00
                                21-30 Licenses - $65  0  0    0.00

above I have included an example of why I would want to be able to either add sub-items or allow for a qty/price of 0

**Comment by AndresMorelos** [comment]
@mcfalld I will review the idea to add sub-items to an item, I'll keep you posted once I've time to start with this issue.

**Comment by AndresMorelos** [comment]
@mcfalld  I just wanted to give you an update: I'm still working on it, finalizing the latest CSS. I expect to release a version of the app with this soon.

**Comment by AndresMorelos** [comment]
@mcfalld, The feature is available from v1.21.0

**Comment by mcfalld** [comment]
thank you just downloaded it!
