### ISSUE TITLE
[FEATURE]: Choose what happens when closing.

### ISSUE THREAD

**Issue by LogGits** [AndresMorelos/Invoncify#87]
**Is your feature request related to a problem? Please describe.**
App remains open after closing (in background)

**Describe the solution you'd like**
It would be nice to be able to be able to choose (in general settings) what happens on closing. E.g. exit/quit on pressing close on main window.

**Comment by AndresMorelos** [comment]
@LogGits Option enabled at general settings on v1.20.0
