### ISSUE TITLE
[FEATURE]: customize the export file name

### ISSUE THREAD

**Issue by mcfalld** [AndresMorelos/Invoncify#94]
It would be cool if there were some settings for the pdf export functionality. For example I'd love to see a way to determine the exported file name. Something like
string{'invoice#'}-${invoice.ID}-${date.month}${invoice.year}

would keep me from having to rename it before sending it to the customer.

**Comment by AndresMorelos** [comment]
@mcfalld I'll take a look at this and l keep you posted

**Comment by mcfalld** [comment]
Hey man you're amazingly responsive and this app is very useful to me. Is there any chance one of the month options could be the month spelled out?

**Comment by AndresMorelos** [comment]
@mcfalld For sure, open a new feature request asking for that.
