### ISSUE TITLE
[BUG]: location of recipient radio buttons

### ISSUE THREAD

**Issue by mcfalld** [AndresMorelos/Invoncify#95]
I dont think this really qualifies as a bug, but I think the 'create new' and 'select' radio buttons should be after the word recipient but just before the form fields. This may be a personal preference thing but just to know that im not creating a new or selecting a product/service.

![image](https://user-images.githubusercontent.com/32588824/174494740-2cbfe82a-5063-475e-9154-b35b170346e2.png)

Again, not a huge deal, just a preference thing. Feel free to close this if you disagree.

**Comment by LogGits** [comment]
I agree with this, it makes more sense to display those things beforehand. Same should be done for `due date` and `discount`.

**Comment by AndresMorelos** [comment]
@LogGits @mcfalld This will be fixed at v1.30.1
